language: ruby

rvm:
 - 2.6.5

services:
  - postgresql

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true



script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rails spec
