language: ruby
rvm:
 - 2.6.5
install: bundle install
services:
  - postgresql
before_script:
  - bundle exec rails db:migrate:reset RAILS_ENV=test
script:
  - bundle exec rails webpacker:compile RAILS_ENV=test
  - bundle exec rails spec